#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MedicationsList.Resource", IsApplication=true)]

namespace MedicationsList
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000f
			public const int aqua = 2130968591;
			
			// aapt resource value: 0x7f040015
			public const int black = 2130968597;
			
			// aapt resource value: 0x7f040013
			public const int blue = 2130968595;
			
			// aapt resource value: 0x7f040000
			public const int cardview_dark_background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cardview_light_background = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cardview_shadow_end_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cardview_shadow_start_color = 2130968579;
			
			// aapt resource value: 0x7f040016
			public const int dark_grey = 2130968598;
			
			// aapt resource value: 0x7f040008
			public const int fuchsia = 2130968584;
			
			// aapt resource value: 0x7f040012
			public const int green = 2130968594;
			
			// aapt resource value: 0x7f04000b
			public const int grey = 2130968587;
			
			// aapt resource value: 0x7f040010
			public const int lime = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int maroon = 2130968590;
			
			// aapt resource value: 0x7f040014
			public const int navy = 2130968596;
			
			// aapt resource value: 0x7f04000c
			public const int olive = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int purple = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int red = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int silver = 2130968586;
			
			// aapt resource value: 0x7f040011
			public const int teal = 2130968593;
			
			// aapt resource value: 0x7f040005
			public const int theme_blue = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int theme_green = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int white = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int yellow = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_compat_inset_shadow = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_default_elevation = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_default_radius = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arr = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrowHeder = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrSmaller = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_bg_stroke = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int calendarMenu = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int calendarSmall = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int chatMenu = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int chatSmall = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int EMG = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int group = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int homePage = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int homeSmall = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_icon1 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_icon2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_icon3 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_icon4 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_icon5 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int medic = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int notifiactionSmall = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int notificationMenu = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int phone = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int prescribedMedications = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int RT = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int RTsmall = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int settingSmall = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int settingSmall2 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int settingsMenu = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080045
			public const int approvedButton = 2131230789;
			
			// aapt resource value: 0x7f080017
			public const int bottomtoolbarmain = 2131230743;
			
			// aapt resource value: 0x7f080010
			public const int button1 = 2131230736;
			
			// aapt resource value: 0x7f080020
			public const int card_view2 = 2131230752;
			
			// aapt resource value: 0x7f080043
			public const int commentText = 2131230787;
			
			// aapt resource value: 0x7f08002c
			public const int container = 2131230764;
			
			// aapt resource value: 0x7f08002b
			public const int content = 2131230763;
			
			// aapt resource value: 0x7f080003
			public const int dateListedLabel = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int dateListedText = 2131230727;
			
			// aapt resource value: 0x7f080022
			public const int doctorNameText = 2131230754;
			
			// aapt resource value: 0x7f08000e
			public const int durationLabel = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int durationText = 2131230735;
			
			// aapt resource value: 0x7f080016
			public const int editText1 = 2131230742;
			
			// aapt resource value: 0x7f08002d
			public const int expandableListView1 = 2131230765;
			
			// aapt resource value: 0x7f08002f
			public const int footer = 2131230767;
			
			// aapt resource value: 0x7f08002e
			public const int footer_border = 2131230766;
			
			// aapt resource value: 0x7f080008
			public const int frequencyLabel = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int frequencyText = 2131230729;
			
			// aapt resource value: 0x7f080019
			public const int header = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int header_menu_left = 2131230746;
			
			// aapt resource value: 0x7f08001e
			public const int header_menu_right = 2131230750;
			
			// aapt resource value: 0x7f08001c
			public const int header_title = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int heading_text = 2131230749;
			
			// aapt resource value: 0x7f08003e
			public const int imageButton1 = 2131230782;
			
			// aapt resource value: 0x7f08003f
			public const int imageButton2 = 2131230783;
			
			// aapt resource value: 0x7f080021
			public const int imageView1 = 2131230753;
			
			// aapt resource value: 0x7f08002a
			public const int imageView2 = 2131230762;
			
			// aapt resource value: 0x7f080029
			public const int imageView3 = 2131230761;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080012
			public const int linearLayout2 = 2131230738;
			
			// aapt resource value: 0x7f080023
			public const int linearLayout3 = 2131230755;
			
			// aapt resource value: 0x7f080046
			public const int linearLayout4 = 2131230790;
			
			// aapt resource value: 0x7f080027
			public const int linearLayout7 = 2131230759;
			
			// aapt resource value: 0x7f080018
			public const int main_content = 2131230744;
			
			// aapt resource value: 0x7f08001b
			public const int menu_left = 2131230747;
			
			// aapt resource value: 0x7f08001f
			public const int menu_right = 2131230751;
			
			// aapt resource value: 0x7f080004
			public const int quantityLabel = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int quantityText = 2131230725;
			
			// aapt resource value: 0x7f080026
			public const int ratingBar1 = 2131230758;
			
			// aapt resource value: 0x7f080015
			public const int ratingbar = 2131230741;
			
			// aapt resource value: 0x7f080044
			public const int rejectButton = 2131230788;
			
			// aapt resource value: 0x7f08000b
			public const int routeLabel = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int routeText = 2131230732;
			
			// aapt resource value: 0x7f080024
			public const int statusTextView = 2131230756;
			
			// aapt resource value: 0x7f080030
			public const int tab1 = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int tab1_icon = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int tab1_text = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int tab2 = 2131230771;
			
			// aapt resource value: 0x7f080034
			public const int tab2_icon = 2131230772;
			
			// aapt resource value: 0x7f080035
			public const int tab2_text = 2131230773;
			
			// aapt resource value: 0x7f080036
			public const int tab3 = 2131230774;
			
			// aapt resource value: 0x7f080037
			public const int tab3_icon = 2131230775;
			
			// aapt resource value: 0x7f080038
			public const int tab3_text = 2131230776;
			
			// aapt resource value: 0x7f080039
			public const int tab4 = 2131230777;
			
			// aapt resource value: 0x7f08003a
			public const int tab4_icon = 2131230778;
			
			// aapt resource value: 0x7f08003b
			public const int tab4_text = 2131230779;
			
			// aapt resource value: 0x7f08003c
			public const int tab5_icon = 2131230780;
			
			// aapt resource value: 0x7f08003d
			public const int tab5_text = 2131230781;
			
			// aapt resource value: 0x7f080001
			public const int tableLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int tableRow1 = 2131230722;
			
			// aapt resource value: 0x7f08000d
			public const int tableRow2 = 2131230733;
			
			// aapt resource value: 0x7f080040
			public const int tableRow3 = 2131230784;
			
			// aapt resource value: 0x7f080006
			public const int tableRow4 = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int tableRow5 = 2131230730;
			
			// aapt resource value: 0x7f080025
			public const int telephoneTextView = 2131230757;
			
			// aapt resource value: 0x7f080011
			public const int textView1 = 2131230737;
			
			// aapt resource value: 0x7f080041
			public const int textView14 = 2131230785;
			
			// aapt resource value: 0x7f080013
			public const int textView2 = 2131230739;
			
			// aapt resource value: 0x7f080042
			public const int textView20 = 2131230786;
			
			// aapt resource value: 0x7f080014
			public const int textView3 = 2131230740;
			
			// aapt resource value: 0x7f080028
			public const int titleText = 2131230760;
			
			// aapt resource value: 0x7f080047
			public const int visitsExpandableListView = 2131230791;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Evaluate = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EvaluatedPage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ExpandedMedicationItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Header = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int layout1 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int List = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MedicationDetail = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Rejection = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RejectionDetail = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Schedule = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int VisitItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int VisitItem_Approved = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int VisitItem_Evaluated = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int VisitItem_Proposed = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Visits_Test = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int VisitsDetail = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int VisitsList = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070004
			public const int ApplicationName = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int sessions_tab_label = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int speakers_tab_label = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int whatson_tab_label = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Base_CardView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int CardView = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int CardView_Light = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int button_text = 2131099652;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
